Repository derian-cordoba/secure-keys, pull requests merged in 2025-02, with the labels that each got.

#3 Added Ruby gem compatibility
  .gitignore
  Gemfile
  Gemfile.lock
  README.md
  bin/secure-keys
  lib/version.rb
  secure-keys.gemspec
Labels: enhancement

#4 Create homebrew formula
  Formula/secure_keys.rb
  README.md
  lib/version.rb
  secure-keys.gemspec
Labels: enhancement

#5 Fix Homebrew formula
  Formula/secure_keys.rb
  README.md
Labels: bug

#7 Create GitHub page integration
  docs/index.md
Labels: documentation, enhancement

#9 Added `dotenv` dependency
  Gemfile.lock
  bin/secure-keys
  docs/index.md
  lib/version.rb
  secure-keys.gemspec
Labels: documentation, enhancement

#10 Updated Homebrew formula
  Formula/secure_keys.rb
Labels: enhancement

#11 Rename iOS key target from `Keys` to `SecureKeys`
  .gitignore
  Formula/secure_keys.rb
  Gemfile.lock
  README.md
  bin/secure-keys
  docs/assets/add-xcframework-to-ios-project/fourth-step.png
  docs/assets/add-xcframework-to-ios-project/third-step-result.png
  docs/assets/add-xcframework-to-ios-project/third-step.png
  docs/index.md
  lib/core/environment/ci.rb
  lib/core/environment/keychain.rb
  lib/core/globals/globals.rb
  lib/core/utils/openssl/cipher.rb
  lib/core/utils/swift/package.rb
  lib/core/utils/swift/swift.rb
  lib/core/utils/swift/writer.rb
  lib/core/utils/swift/xcframework.rb
  lib/keys.rb
  lib/version.rb
  secure-keys.gemspec
Labels: enhancement

#12 Updated homebrew formula
  Formula/secure_keys.rb
Labels: enhancement

#13 Remove formula references from main repository
  Formula/secure_keys.rb
  README.md
  docs/index.md
Labels: enhancement

#15 CLI Integration
  Gemfile.lock
  README.md
  docs/index.md
  lib/core/console/arguments/handler.rb
  lib/core/console/arguments/parser.rb
  lib/core/globals/globals.rb
  lib/keys.rb
  lib/version.rb
  secure-keys.gemspec
Labels: documentation, enhancement

#16 Implement integration tests
  .github/workflows/tests.yml
  .gitignore
  .rspec
  Gemfile.lock
  secure-keys.gemspec
  spec/core/console/arguments/parser_spec.rb
  spec/core/globals/globals_spec.rb
  spec/helpers/arguments/handler.rb
  spec/helpers/simplecov_env.rb
  spec/spec_helper.rb
Labels: enhancement

#17 Implement Logger system
  Gemfile.lock
  README.md
  docs/index.md
  lib/core/console/arguments/handler.rb
  lib/core/console/arguments/parser.rb
  lib/core/console/logger.rb
  lib/core/console/shell.rb
  lib/core/globals/globals.rb
  lib/core/utils/swift/package.rb
  lib/core/utils/swift/xcframework.rb
  secure-keys.gemspec
  spec/core/console/arguments/parser_spec.rb
  spec/core/globals/globals_spec.rb
  spec/helpers/arguments/handler.rb
Labels: enhancement

#18 Create UIKit app fixture
  fixtures/UIKitFirebaseApp/README.md
  fixtures/UIKitFirebaseApp/UIKitApp.xcodeproj/project.pbxproj
  fixtures/UIKitFirebaseApp/UIKitApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  fixtures/UIKitFirebaseApp/UIKitApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  fixtures/UIKitFirebaseApp/UIKitApp.xcodeproj/project.xcworkspace/xcuserdata/deriancordoba.xcuserdatad/UserInterfaceState.xcuserstate
  fixtures/UIKitFirebaseApp/UIKitApp.xcodeproj/xcuserdata/deriancordoba.xcuserdatad/xcschemes/xcschememanagement.plist
  fixtures/UIKitFirebaseApp/UIKitApp/AppDelegate.swift
  fixtures/UIKitFirebaseApp/UIKitApp/Assets.xcassets/AccentColor.colorset/Contents.json
  fixtures/UIKitFirebaseApp/UIKitApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  fixtures/UIKitFirebaseApp/UIKitApp/Assets.xcassets/Contents.json
  fixtures/UIKitFirebaseApp/UIKitApp/Base.lproj/LaunchScreen.storyboard
  fixtures/UIKitFirebaseApp/UIKitApp/Base.lproj/Main.storyboard
  fixtures/UIKitFirebaseApp/UIKitApp/GoogleService-Info.plist
  fixtures/UIKitFirebaseApp/UIKitApp/Info.plist
  fixtures/UIKitFirebaseApp/UIKitApp/SceneDelegate.swift
  fixtures/UIKitFirebaseApp/UIKitApp/ViewController.swift
  fixtures/UIKitFirebaseApp/docs/assets/app-delegate-swift-file.png
  fixtures/UIKitFirebaseApp/docs/assets/run-xcode-app.gif
Labels: documentation, enhancement

#19 Add `SecureKeys` xcframework automatically from CLI
  Gemfile.lock
  README.md
  docs/index.md
  lib/core/console/arguments/handler.rb
  lib/core/console/arguments/parser.rb
  lib/core/globals/globals.rb
  lib/core/utils/swift/xcframework.rb
  lib/core/utils/swift/xcodeproj.rb
  secure-keys.gemspec
  spec/core/console/arguments/parser_spec.rb
  spec/core/utils/xcodeproj_spec.rb
  spec/fixtures/ios/SecureKeys/SecureKeys.xcodeproj/project.pbxproj
Labels: documentation, enhancement

#21 Create SwiftUI + Backend fixture
  .gitignore
  fixtures/SwiftUIApp+Backend/README.md
  fixtures/SwiftUIApp+Backend/backend/.gitignore
  fixtures/SwiftUIApp+Backend/backend/README.md
  fixtures/SwiftUIApp+Backend/backend/package-lock.json
  fixtures/SwiftUIApp+Backend/backend/package.json
  fixtures/SwiftUIApp+Backend/backend/src/app.js
  fixtures/SwiftUIApp+Backend/client/SwiftUIApp.xcodeproj/project.pbxproj
  fixtures/SwiftUIApp+Backend/client/SwiftUIApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  fixtures/SwiftUIApp+Backend/client/SwiftUIApp.xcodeproj/project.xcworkspace/xcuserdata/deriancordoba.xcuserdatad/UserInterfaceState.xcuserstate
  fixtures/SwiftUIApp+Backend/client/SwiftUIApp.xcodeproj/xcuserdata/deriancordoba.xcuserdatad/xcschemes/xcschememanagement.plist
  fixtures/SwiftUIApp+Backend/client/SwiftUIApp/Assets.xcassets/AccentColor.colorset/Contents.json
  fixtures/SwiftUIApp+Backend/client/SwiftUIApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  fixtures/SwiftUIApp+Backend/client/SwiftUIApp/Assets.xcassets/Contents.json
  fixtures/SwiftUIApp+Backend/client/SwiftUIApp/ContentView.swift
  fixtures/SwiftUIApp+Backend/client/SwiftUIApp/Preview Content/Preview Assets.xcassets/Contents.json
  fixtures/SwiftUIApp+Backend/client/SwiftUIApp/SwiftUIAppApp.swift
  fixtures/SwiftUIApp+Backend/docs/assets/swiftui-secure-keys.png
  fixtures/SwiftUIApp+Backend/setup
  lib/version.rb
Labels: documentation, enhancement
